In [7]:
def fac_count(a):
    c=0
    for i in range(1,a+1):
        if a%i==0:
            c=c+1
    return c

In [8]:
def isprime(a):
    fc=fac_count(a)
    if fc==2:
        return True
    return False

In [9]:
i=int(input("Enter a number:"))
if isprime(i):
    print("is Prime")
else:
    print("Not a Prime")

Enter a number:23
is Prime


In [12]:
lb=2
ub=100
def prim_range(lb,ub):
    prim_range(lb,ub)
    for i in range(1,ub+1):
        if isprime(i):
            print(i)

In [2]:
i=input().split()

python program


In [10]:
list(map(str,input()))

python


['p', 'y', 't', 'h', 'o', 'n']

In [13]:
def addition(n):
    return n+n

In [15]:
list(map(addition,[23,7,19,98]))

[46, 14, 38, 196]

In [26]:
def power(n):
    return n**n

In [28]:
list(map(power,[4,7,5,1,0]))

[256, 823543, 3125, 1, 1]

In [29]:
def sqrt(n):
    return n*n

In [33]:
l=list(map(sqrt,[1,2,3,4,5,6]))
for i in l:
    print(i)

1
4
9
16
25
36


In [1]:
L1=[1,2,'a','b','c',3]
def isDigit(n):
    n=str(n)
    if n.isdigit():
        return True
    return False
list(filter(isDigit,L1))

[1, 2, 3]

In [6]:
def iseven(n):
    if n%2==0:
        return True
    return False
def isodd(n):
    if n%2!=0:
        return True
    return False

In [46]:
Li=[2,3,5,7,9,42,98,6,10]
def isDigit(n):
    n=str(n)
    if n.isodd(n): 
        return True
    return False
list(filter(isodd,Li))

NameError: name 'isodd' is not defined

In [4]:
h=lambda x : x%2==0
list(filter(h,[1,2,3,4,5]))

[2, 4]

In [6]:
l=[1,2,3,4,5,6,7,8,9,10]
o=lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [14]:
from random import randint as r
for i in range(1,10+1):
    print(r(1,25))

2
13
3
2
9
1
14
16
16
24


In [18]:
print([i for i in range(1,11) if i%2==0])

[2, 4, 6, 8, 10]


In [24]:
m1=[r(1,25) for i in range(1,11)]
m2=[r(1,25) for i in range(1,11)]
m3=[r(1,25) for i in range(1,11)]
print(m1)
print(m2)
print(m3)

[19, 9, 8, 17, 17, 21, 19, 7, 21, 13]
[20, 6, 17, 3, 8, 10, 21, 6, 19, 11]
[18, 13, 10, 14, 1, 24, 15, 22, 2, 25]


In [25]:
a1=list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[19, 7, 12, 10, 12, 15, 20, 6, 20, 12]


In [29]:
print(12+24)

36


In [28]:
print(36/2)

18.0


In [37]:
a2=list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)

[19, 9, 11, 11, 8, 18, 18, 11, 14, 16]


In [42]:
print(list(filter(lambda x:x<10,a2)))

[9, 8]


In [43]:
print(list(filter(lambda x:x<10,a1)))

[7, 6]


In [47]:
import numpy as np

In [49]:
l=[1,2,3,4,5]
a1=np.array(l)
print(a1)

[1 2 3 4 5]


In [50]:
l2=[[1,2,3],[4,5,6]]
a2=np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]]


In [51]:
l3=[[1,2,3],[4,5,6],[7,8,9]]
a3=np.array(l3)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
a=np.arange(100).reshape(5,20)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [84]:
b=np.arange(20,26).reshape(2,3)
print(b)

[[20 21 22]
 [23 24 25]]


In [85]:
c=np.arange(30,36).reshape(2,3)
print(c)

[[30 31 32]
 [33 34 35]]


In [86]:
d=np.arange(40,46).reshape(2,3)
print(d)

[[40 41 42]
 [43 44 45]]


In [90]:
e=np.arange(50,56).reshape(2,3)
print(e)

[[50 51 52]
 [53 54 55]]
